In [1]:
import duckdb
import pandas as pd

# 데이터베이스 경로
db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'
replica_db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data_replica.db'

print(f"Main DB path: {db_path}")
print(f"Replica DB path: {replica_db_path}")

# 파일 존재 확인
import os
print(f"Main DB exists: {os.path.exists(db_path)}")
print(f"Replica DB exists: {os.path.exists(replica_db_path)}")

Main DB path: /home/grey1/stock-kafka3/data/duckdb/stock_data.db
Replica DB path: /home/grey1/stock-kafka3/data/duckdb/stock_data_replica.db
Main DB exists: False
Replica DB exists: True

In [2]:
import duckdb

# 데이터베이스 경로
db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'

# DuckDB 연결
con = duckdb.connect(database=db_path, read_only=True)

# 테이블 목록 확인
tables = con.execute("SHOW TABLES").fetchall()
print("Tables in database:", tables)

con.close()

IOException: IO Error: Cannot open database "/home/grey1/stock-kafka3/data/duckdb/stock_data.db" in read-only mode: database does not exist

In [2]:
con = duckdb.connect(database=db_path, read_only=True)

In [4]:
nasdaq_symbols = con.execute("SELECT * FROM nasdaq_symbols").fetchall()

In [7]:
import pandas as pd

# 컬럼명 지정
columns = ['symbol', 'name', 'market_cap', 'sector', 'created_at']

# fetchall 결과를 DataFrame으로 변환
nasdaq_symbols = con.execute("SELECT * FROM nasdaq_symbols").fetchall()
df = pd.DataFrame(nasdaq_symbols, columns=columns)

# 결과 확인
df.head()

,symbol,name,market_cap,sector,created_at
0,AAPL,Apple Inc. Common Stock,3154147734680.00,Technology,2025-07-20 06:38:41.613105
1,MSFT,Microsoft Corporation Common Stock,3790968998343.00,Technology,2025-07-20 06:38:41.613105
2,GOOGL,Alphabet Inc. Class A Common Stock,2245703100000.00,Technology,2025-07-20 06:38:41.613105
3,AMZN,Amazon.com Inc. Common Stock,2400675769795.00,Consumer Discretionary,2025-07-20 06:38:41.613105
4,TSLA,Tesla Inc. Common Stock,1061788214956.00,Consumer Discretionary,2025-07-20 06:38:41.613105

In [3]:
# DuckDB 연결
con = duckdb.connect(database=db_path, read_only=True)
import pandas as pd 
columns = [i[1] for i in con.execute("PRAGMA table_info('stock_data')").fetchall()]
stockdf = pd.DataFrame(con.execute("SELECT * FROM stock_data").fetchall(), columns=columns)

In [12]:
stockdf[stockdf['symbol'] == 'AMZN'].sort_values('date', ascending=True).head(10)

,symbol,date,open,high,low,close,volume
0,AMZN,2024-07-22,185.000000,185.059998,182.479996,182.550003,39931900
1,AMZN,2024-07-23,184.100006,189.389999,183.559998,186.410004,47537700
2,AMZN,2024-07-24,183.199997,185.449997,180.410004,180.830002,41532400
3,AMZN,2024-07-25,182.910004,183.899994,176.800003,179.850006,44464200
4,AMZN,2024-07-26,180.389999,183.190002,180.240005,182.500000,29506000
5,AMZN,2024-07-29,183.839996,184.750000,182.380005,183.199997,33270100
6,AMZN,2024-07-30,184.720001,185.860001,179.380005,181.710007,39508600
7,AMZN,2024-07-31,185.050003,187.940002,184.460007,186.979996,41667300
8,AMZN,2024-08-01,189.289993,190.600006,181.869995,184.070007,70435600
9,AMZN,2024-08-02,166.750000,168.770004,160.550003,167.899994,141448400

In [19]:
# DuckDB 연결
con = duckdb.connect(database=db_path, read_only=True)
import pandas as pd 
columns = [i[1] for i in con.execute("PRAGMA table_info('stock_data_technical_indicators')").fetchall()]
stock_data_technical_indicators = pd.DataFrame(con.execute("SELECT * FROM stock_data_technical_indicators").fetchall(), columns=columns)

In [24]:
stock_data_technical_indicators

,symbol,date,bb_upper,bb_middle,bb_lower,macd,macd_signal,macd_histogram,rsi,sma_5,sma_20,sma_60,ema_5,ema_20,ema_60,cci,obv,ma_112,ma_224,ma_448
0,AAL,2024-07-22,NaN,10.690000,NaN,0.000000,0.000000,0.000000,NaN,10.690000,10.690000,10.690000,10.690000,10.690000,10.690000,NaN,0,10.690000,10.690000,10.690000
1,AAL,2024-07-23,10.881984,10.585000,10.288015,-0.008376,-0.004188,-0.004188,0.000000,10.585000,10.585000,10.585000,10.550000,10.575000,10.581557,NaN,-30548000,10.585000,10.585000,10.585000
2,AAL,2024-07-24,10.969861,10.446666,9.923472,-0.022070,-0.010149,-0.011921,0.000000,10.446666,10.446666,10.446666,10.354444,10.420317,10.437595,NaN,-77860000,10.446666,10.446666,10.446666
3,AAL,2024-07-25,10.938872,10.485000,10.031128,0.009174,-0.005318,0.014492,45.263199,10.485000,10.485000,10.485000,10.523333,10.495952,10.488770,NaN,18420800,10.485000,10.485000,10.485000
4,AAL,2024-07-26,10.923193,10.512000,10.100807,0.008615,-0.002531,0.011147,46.391766,10.512000,10.512000,10.512000,10.548000,10.522286,10.515541,NaN,64105300,10.512000,10.512000,10.512000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,AMZN,2025-07-15,229.733390,218.732502,207.731614,4.793112,3.851846,0.941266,70.688593,224.372000,218.732502,205.348334,225.031335,219.457979,206.036914,NaN,430641800,204.977322,204.070715,201.484472
1118,AMZN,2025-07-16,230.187203,219.087002,207.986801,4.190683,3.954270,0.236413,65.909074,224.502002,219.087002,206.191334,224.064669,219.477764,206.748668,NaN,391105900,204.850268,204.263036,201.572349
1119,AMZN,2025-07-17,230.646474,219.540002,208.433530,4.316602,4.051290,0.265312,60.988298,224.826004,219.540002,207.134001,224.510671,219.953335,207.683050,NaN,422961700,204.687947,204.476206,201.662299
1120,AMZN,2025-07-18,231.182794,220.220502,209.258209,4.592478,4.184854,0.407624,55.273944,225.048004,220.220502,208.016501,225.408671,220.783312,208.610386,NaN,460773300,204.598304,204.695358,201.760563
1121,AMZN,2025-07-21,231.458391,221.142502,210.826612,4.799237,4.378282,0.420956,67.536106,225.536005,221.142502,208.808668,226.400671,221.807978,209.442154,NaN,477036671,204.502768,204.930313,201.866040

In [22]:
# DuckDB 연결
con = duckdb.connect(database=db_path, read_only=True)
import pandas as pd 
columns = [i[1] for i in con.execute("PRAGMA table_info('stock_technical_indicators')").fetchall()]
stock_technical_indicators = pd.DataFrame(con.execute("SELECT * FROM stock_technical_indicators").fetchall(), columns=columns)

In [23]:
stock_technical_indicators

,symbol,date,close_price,bb_middle,bb_upper,bb_lower,price_change
0,AAL,2024-07-22,10.690000,10.690000,NaN,NaN,NaN
1,AAL,2024-07-23,10.480000,10.585000,10.881984,10.288015,-0.210000
2,AAL,2024-07-24,10.170000,10.446666,10.969861,9.923472,-0.309999
3,AAL,2024-07-25,10.600000,10.485000,10.938872,10.031128,0.430000
4,AAL,2024-07-26,10.620000,10.512000,10.923193,10.100807,0.020000
...,...,...,...,...,...,...,...
1117,AMZN,2025-07-15,226.350006,218.732502,229.733390,207.731614,0.660004
1118,AMZN,2025-07-16,223.190002,219.087002,230.187203,207.986801,-3.160004
1119,AMZN,2025-07-17,223.880005,219.540002,230.646474,208.433530,0.690002
1120,AMZN,2025-07-18,226.130005,220.220502,231.182794,209.258209,2.250000
1121,AMZN,2025-07-21,228.130005,221.142502,231.458391,210.826612,2.000000

In [26]:
import yfinance as yf
ticker = yf.Ticker('AAPL')
info = ticker.fast_info
hist = ticker.history(period="1d", interval="1m").tail(1)

In [27]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-07-22 11:24:00-04:00,213.350998,213.350998,213.350998,213.350998,0,0.0,0.0

In [9]:
con.execute("SELECT * FROM stock_data").fetchall()

[('AMZN',
  datetime.date(2024, 7, 22),
  185.0,
  185.05999755859375,
  182.47999572753906,
  182.5500030517578,
  39931900),
 ('AMZN',
  datetime.date(2024, 7, 23),
  184.10000610351562,
  189.38999938964844,
  183.55999755859375,
  186.41000366210938,
  47537700),
 ('AMZN',
  datetime.date(2024, 7, 24),
  183.1999969482422,
  185.4499969482422,
  180.41000366210938,
  180.8300018310547,
  41532400),
 ('AMZN',
  datetime.date(2024, 7, 25),
  182.91000366210938,
  183.89999389648438,
  176.8000030517578,
  179.85000610351562,
  44464200),
 ('AMZN',
  datetime.date(2024, 7, 26),
  180.38999938964844,
  183.19000244140625,
  180.24000549316406,
  182.5,
  29506000),
 ('AMZN',
  datetime.date(2024, 7, 29),
  183.83999633789062,
  184.75,
  182.3800048828125,
  183.1999969482422,
  33270100),
 ('AMZN',
  datetime.date(2024, 7, 30),
  184.72000122070312,
  185.86000061035156,
  179.3800048828125,
  181.7100067138672,
  39508600),
 ('AMZN',
  datetime.date(2024, 7, 31),
  185.0500030517578,
  187.94000244140625,
  184.4600067138672,
  186.97999572753906,
  41667300),
 ('AMZN',
  datetime.date(2024, 8, 1),
  189.2899932861328,
  190.60000610351562,
  181.8699951171875,
  184.07000732421875,
  70435600),
 ('AMZN',
  datetime.date(2024, 8, 2),
  166.75,
  168.77000427246094,
  160.5500030517578,
  167.89999389648438,
  141448400),
 ('AMZN',
  datetime.date(2024, 8, 5),
  154.2100067138672,
  162.9600067138672,
  151.61000061035156,
  161.02000427246094,
  83149400),
 ('AMZN',
  datetime.date(2024, 8, 6),
  161.7100067138672,
  165.0800018310547,
  158.5399932861328,
  161.92999267578125,
  59950800),
 ('AMZN',
  datetime.date(2024, 8, 7),
  166.5500030517578,
  167.5800018310547,
  161.42999267578125,
  162.77000427246094,
  48408200),
 ('AMZN',
  datetime.date(2024, 8, 8),
  165.1699981689453,
  166.69000244140625,
  162.5500030517578,
  165.8000030517578,
  44616200),
 ('AMZN',
  datetime.date(2024, 8, 9),
  166.39999389648438,
  168.5500030517578,
  165.85000610351562,
  166.94000244140625,
  36401000),
 ('AMZN',
  datetime.date(2024, 8, 12),
  168.13999938964844,
  168.5500030517578,
  166.11000061035156,
  166.8000030517578,
  30072800),
 ('AMZN',
  datetime.date(2024, 8, 13),
  167.80999755859375,
  171.0399932861328,
  167.10000610351562,
  170.22999572753906,
  39237900),
 ('AMZN',
  datetime.date(2024, 8, 14),
  172.11000061035156,
  172.27999877929688,
  168.86000061035156,
  170.10000610351562,
  28843800),
 ('AMZN',
  datetime.date(2024, 8, 15),
  174.86000061035156,
  177.91000366210938,
  173.99000549316406,
  177.58999633789062,
  51698500),
 ('AMZN',
  datetime.date(2024, 8, 16),
  177.0399932861328,
  178.33999633789062,
  176.25999450683594,
  177.05999755859375,
  31489200),
 ('AMZN',
  datetime.date(2024, 8, 19),
  177.63999938964844,
  178.3000030517578,
  176.16000366210938,
  178.22000122070312,
  31129800),
 ('AMZN',
  datetime.date(2024, 8, 20),
  177.9199981689453,
  179.00999450683594,
  177.42999267578125,
  178.8800048828125,
  26255200),
 ('AMZN',
  datetime.date(2024, 8, 21),
  179.9199981689453,
  182.38999938964844,
  178.88999938964844,
  180.11000061035156,
  35599100),
 ('AMZN',
  datetime.date(2024, 8, 22),
  181.3800048828125,
  181.47000122070312,
  175.67999267578125,
  176.1300048828125,
  32047500),
 ('AMZN',
  datetime.date(2024, 8, 23),
  177.33999633789062,
  178.97000122070312,
  175.24000549316406,
  177.0399932861328,
  29150100),
 ('AMZN',
  datetime.date(2024, 8, 26),
  176.6999969482422,
  177.47000122070312,
  174.3000030517578,
  175.5,
  22366200),
 ('AMZN',
  datetime.date(2024, 8, 27),
  174.14999389648438,
  174.88999938964844,
  172.25,
  173.1199951171875,
  29842000),
 ('AMZN',
  datetime.date(2024, 8, 28),
  173.69000244140625,
  173.69000244140625,
  168.9199981689453,
  170.8000030517578,
  29045000),
 ('AMZN',
  datetime.date(2024, 8, 29),
  173.22000122070312,
  174.2899932861328,
  170.80999755859375,
  172.1199951171875,
  26407800),
 ('AMZN',
  datetime.date(2024, 8, 30),
  172.77999877929688,
  178.89999389648438,
  172.60000610351562,
  178.5,
  43429400),
 ('AMZN',
  datetime.date(2024, 9, 3),
  177.5500030517578,
  178.25999450683594,
  175.25999450683594,
  176.25,
  37817500),
 ('AMZN',
  datetime.date(2024, 9, 4),
  174.47999572753906,
  175.97999572753906,
  172.5399932861328,
  173.3300018310547,
  30309200),
 ('AMZN',
  datetime.date(2024, 9, 5),
  175.0,
  179.8800048828125,
  175.0,
  177.88999938964844,
  40170500),
 ('AMZN',
  datetime.date(2024, 9, 6),
  177.24000549316406,
  178.3800048828125,
  171.16000366210938,
  171.38999938964844,
  41466500),
 ('AMZN',
  datetime.date(2024, 9, 9),
  174.52999877929688,
  175.85000610351562,
  173.50999450683594,
  175.39999389648438,
  29037400),
 ('AMZN',
  datetime.date(2024, 9, 10),
  177.49000549316406,
  180.5,
  176.7899932861328,
  179.5500030517578,
  36233800),
 ('AMZN',
  datetime.date(2024, 9, 11),
  180.10000610351562,
  184.99000549316406,
  175.72999572753906,
  184.52000427246094,
  42564700),
 ('AMZN',
  datetime.date(2024, 9, 12),
  184.8000030517578,
  187.41000366210938,
  183.5399932861328,
  187.0,
  33544200),
 ('AMZN',
  datetime.date(2024, 9, 13),
  187.0,
  188.5,
  185.91000366210938,
  186.49000549316406,
  26495400),
 ('AMZN',
  datetime.date(2024, 9, 16),
  185.2899932861328,
  185.80999755859375,
  183.36000061035156,
  184.88999938964844,
  26065500),
 ('AMZN',
  datetime.date(2024, 9, 17),
  186.85000610351562,
  189.4499969482422,
  186.13999938964844,
  186.8800048828125,
  26091700),
 ('AMZN',
  datetime.date(2024, 9, 18),
  186.4499969482422,
  188.8000030517578,
  185.05999755859375,
  186.42999267578125,
  34448100),
 ('AMZN',
  datetime.date(2024, 9, 19),
  190.0399932861328,
  190.99000549316406,
  188.47000122070312,
  189.8699951171875,
  39543200),
 ('AMZN',
  datetime.date(2024, 9, 20),
  190.22999572753906,
  191.83999633789062,
  187.41000366210938,
  191.60000610351562,
  100378600),
 ('AMZN',
  datetime.date(2024, 9, 23),
  191.63999938964844,
  194.4499969482422,
  190.57000732421875,
  193.8800048828125,
  36993100),
 ('AMZN',
  datetime.date(2024, 9, 24),
  194.27000427246094,
  195.3699951171875,
  190.1300048828125,
  193.9600067138672,
  43478900),
 ('AMZN',
  datetime.date(2024, 9, 25),
  193.75,
  193.9499969482422,
  192.16000366210938,
  192.52999877929688,
  26391100),
 ('AMZN',
  datetime.date(2024, 9, 26),
  194.30999755859375,
  194.52999877929688,
  189.5399932861328,
  191.16000366210938,
  36334900),
 ('AMZN',
  datetime.date(2024, 9, 27),
  190.67999267578125,
  190.89999389648438,
  187.33999633789062,
  187.97000122070312,
  36002300),
 ('AMZN',
  datetime.date(2024, 9, 30),
  187.13999938964844,
  188.49000549316406,
  184.64999389648438,
  186.3300018310547,
  41583900),
 ('AMZN',
  datetime.date(2024, 10, 1),
  184.89999389648438,
  186.19000244140625,
  183.4499969482422,
  185.1300048828125,
  36044900),
 ('AMZN',
  datetime.date(2024, 10, 2),
  184.44000244140625,
  186.60000610351562,
  184.0399932861328,
  184.75999450683594,
  23704100),
 ('AMZN',
  datetime.date(2024, 10, 3),
  183.0500030517578,
  183.44000244140625,
  180.8800048828125,
  181.9600067138672,
  30204300),
 ('AMZN',
  datetime.date(2024, 10, 4),
  185.75,
  187.60000610351562,
  183.60000610351562,
  186.50999450683594,
  40890300),
 ('AMZN',
  datetime.date(2024, 10, 7),
  182.9499969482422,
  183.60000610351562,
  180.25,
  180.8000030517578,
  42364200),
 ('AMZN',
  datetime.date(2024, 10, 8),
  181.9199981689453,
  183.08999633789062,
  180.9199981689453,
  182.72000122070312,
  26372100),
 ('AMZN',
  datetime.date(2024, 10, 9),
  182.82000732421875,
  185.85000610351562,
  182.0500030517578,
  185.1699981689453,
  26343100),
 ('AMZN',
  datetime.date(2024, 10, 10),
  187.1300048828125,
  188.1300048828125,
  185.8300018310547,
  186.64999389648438,
  27785000),
 ('AMZN',
  datetime.date(2024, 10, 11),
  186.6300048828125,
  189.92999267578125,
  186.3000030517578,
  188.82000732421875,
  25751600),
 ('AMZN',
  datetime.date(2024, 10, 14),
  189.77999877929688,
  189.8300018310547,
  187.36000061035156,
  187.5399932861328,
  22614400),
 ('AMZN',
  datetime.date(2024, 10, 15),
  187.6300048828125,
  188.41000366210938,
  184.5800018310547,
  187.69000244140625,
  32178900),
 ('AMZN',
  datetime.date(2024, 10, 16),
  187.0500030517578,
  187.77999877929688,
  185.61000061035156,
  186.88999938964844,
  23456800),
 ('AMZN',
  datetime.date(2024, 10, 17),
  188.22000122070312,
  188.94000244140625,
  186.0,
  187.52999877929688,
  25039400),
 ('AMZN',
  datetime.date(2024, 10, 18),
  187.14999389648438,
  190.74000549316406,
  186.27999877929688,
  188.99000549316406,
  37417700),
 ('AMZN',
  datetime.date(2024, 10, 21),
  188.0500030517578,
  189.4600067138672,
  186.39999389648438,
  189.07000732421875,
  24639400),
 ('AMZN',
  datetime.date(2024, 10, 22),
  188.35000610351562,
  191.52000427246094,
  186.97999572753906,
  189.6999969482422,
  29650600),
 ('AMZN',
  datetime.date(2024, 10, 23),
  188.85000610351562,
  189.16000366210938,
  183.69000244140625,
  184.7100067138672,
  31937100),
 ('AMZN',
  datetime.date(2024, 10, 24),
  185.25,
  187.11000061035156,
  183.86000061035156,
  186.3800048828125,
  21647400),
 ('AMZN',
  datetime.date(2024, 10, 25),
  187.85000610351562,
  190.4499969482422,
  187.52999877929688,
  187.8300018310547,
  29362100),
 ('AMZN',
  datetime.date(2024, 10, 28),
  189.57000732421875,
  190.2100067138672,
  188.2100067138672,
  188.38999938964844,
  27930800),
 ('AMZN',
  datetime.date(2024, 10, 29),
  188.5800018310547,
  191.4600067138672,
  187.82000732421875,
  190.8300018310547,
  35690200),
 ('AMZN',
  datetime.date(2024, 10, 30),
  194.6999969482422,
  195.61000061035156,
  192.4199981689453,
  192.72999572753906,
  37707600),
 ('AMZN',
  datetime.date(2024, 10, 31),
  190.50999450683594,
  190.60000610351562,
  185.22999572753906,
  186.39999389648438,
  75146800),
 ('AMZN',
  datetime.date(2024, 11, 1),
  199.0,
  200.5,
  197.02000427246094,
  197.92999267578125,
  99687800),
 ('AMZN',
  datetime.date(2024, 11, 4),
  196.4499969482422,
  197.3300018310547,
  194.30999755859375,
  195.77999877929688,
  38492100),
 ('AMZN',
  datetime.date(2024, 11, 5),
  196.0399932861328,
  199.82000732421875,
  195.99000549316406,
  199.5,
  30564800),
 ('AMZN',
  datetime.date(2024, 11, 6),
  200.00999450683594,
  207.5500030517578,
  199.13999938964844,
  207.08999633789062,
  72292200),
 ('AMZN',
  datetime.date(2024, 11, 7),
  207.44000244140625,
  212.25,
  207.19000244140625,
  210.0500030517578,
  52878400),
 ('AMZN',
  datetime.date(2024, 11, 8),
  209.72000122070312,
  209.9600067138672,
  207.44000244140625,
  208.17999267578125,
  36075800),
 ('AMZN',
  datetime.date(2024, 11, 11),
  208.5,
  209.64999389648438,
  205.58999633789062,
  206.83999633789062,
  35456000),
 ('AMZN',
  datetime.date(2024, 11, 12),
  208.3699951171875,
  209.5399932861328,
  206.00999450683594,
  208.91000366210938,
  38942900),
 ('AMZN',
  datetime.date(2024, 11, 13),
  209.39999389648438,
  215.08999633789062,
  209.13999938964844,
  214.10000610351562,
  46212900),
 ('AMZN',
  datetime.date(2024, 11, 14),
  214.16000366210938,
  215.89999389648438,
  210.8800048828125,
  211.47999572753906,
  42620300),
 ('AMZN',
  datetime.date(2024, 11, 15),
  206.75999450683594,
  207.33999633789062,
  199.61000061035156,
  202.61000061035156,
  86591100),
 ('AMZN',
  datetime.date(2024, 11, 18),
  204.14999389648438,
  204.6699981689453,
  200.9499969482422,
  201.6999969482422,
  36409900),
 ('AMZN',
  datetime.date(2024, 11, 19),
  199.3300018310547,
  205.3000030517578,
  198.77999877929688,
  204.61000061035156,
  31197900),
 ('AMZN',
  datetime.date(2024, 11, 20),
  202.97999572753906,
  203.1300048828125,
  199.4499969482422,
  202.8800048828125,
  32769000),
 ('AMZN',
  datetime.date(2024, 11, 21),
  203.49000549316406,
  203.49000549316406,
  195.75,
  198.3800048828125,
  58800000),
 ('AMZN',
  datetime.date(2024, 11, 22),
  198.25,
  199.25999450683594,
  196.75,
  197.1199951171875,
  31530800),
 ('AMZN',
  datetime.date(2024, 11, 25),
  199.27999877929688,
  201.9499969482422,
  199.0,
  201.4499969482422,
  40685700),
 ('AMZN',
  datetime.date(2024, 11, 26),
  201.89999389648438,
  208.0,
  201.7899932861328,
  207.86000061035156,
  41673700),
 ('AMZN',
  datetime.date(2024, 11, 27),
  206.97999572753906,
  207.63999938964844,
  205.0500030517578,
  205.74000549316406,
  28061600),
 ('AMZN',
  datetime.date(2024, 11, 29),
  205.8300018310547,
  208.1999969482422,
  204.58999633789062,
  207.88999938964844,
  24892400),
 ('AMZN',
  datetime.date(2024, 12, 2),
  209.9600067138672,
  212.99000549316406,
  209.50999450683594,
  210.7100067138672,
  39523200),
 ('AMZN',
  datetime.date(2024, 12, 3),
  210.30999755859375,
  214.02000427246094,
  209.64999389648438,
  213.44000244140625,
  32214800),
 ('AMZN',
  datetime.date(2024, 12, 4),
  215.9600067138672,
  220.0,
  215.75,
  218.16000366210938,
  48745700),
 ('AMZN',
  datetime.date(2024, 12, 5),
  218.02999877929688,
  222.14999389648438,
  217.3000030517578,
  220.5500030517578,
  41140200),
 ('AMZN',
  datetime.date(2024, 12, 6),
  220.75,
  227.14999389648438,
  220.60000610351562,
  227.02999877929688,
  44178100),
 ('AMZN',
  datetime.date(2024, 12, 9),
  227.2100067138672,
  230.0800018310547,
  225.6699981689453,
  226.08999633789062,
  46819400),
 ('AMZN',
  datetime.date(2024, 12, 10),
  226.08999633789062,
  229.05999755859375,
  224.1999969482422,
  225.0399932861328,
  31199900),
 ('AMZN',
  datetime.date(2024, 12, 11),
  226.41000366210938,
  231.1999969482422,
  226.25999450683594,
  230.25999450683594,
  35385800),
 ('AMZN',
  datetime.date(2024, 12, 12),
  229.8300018310547,
  231.08999633789062,
  227.6300048828125,
  228.97000122070312,
  28204100),
 ('AMZN',
  datetime.date(2024, 12, 13),
  228.39999389648438,
  230.1999969482422,
  225.86000061035156,
  227.4600067138672,
  28768100),
 ('AMZN',
  datetime.date(2024, 12, 16),
  230.22999572753906,
  233.0,
  228.00999450683594,
  232.92999267578125,
  37552100),
 ('AMZN',
  datetime.date(2024, 12, 17),
  232.38999938964844,
  232.72999572753906,
  227.85000610351562,
  231.14999389648438,
  35948100),
 ('AMZN',
  datetime.date(2024, 12, 18),
  230.77000427246094,
  231.39999389648438,
  220.11000061035156,
  220.52000427246094,
  43281400),
 ('AMZN',
  datetime.date(2024, 12, 19),
  224.91000366210938,
  226.08999633789062,
  222.9199981689453,
  223.2899932861328,
  39918700),
 ('AMZN',
  datetime.date(2024, 12, 20),
  219.83999633789062,
  226.2100067138672,
  218.72999572753906,
  224.9199981689453,
  88279200),
 ('AMZN',
  datetime.date(2024, 12, 23),
  225.00999450683594,
  226.8800048828125,
  223.89999389648438,
  225.05999755859375,
  28070000),
 ('AMZN',
  datetime.date(2024, 12, 24),
  226.94000244140625,
  229.13999938964844,
  226.1300048828125,
  229.0500030517578,
  15007500),
 ('AMZN',
  datetime.date(2024, 12, 26),
  228.5,
  228.5,
  226.6699981689453,
  227.0500030517578,
  16146700),
 ('AMZN',
  datetime.date(2024, 12, 27),
  225.60000610351562,
  226.02999877929688,
  220.89999389648438,
  223.75,
  27367100),
 ('AMZN',
  datetime.date(2024, 12, 30),
  220.05999755859375,
  223.0,
  218.42999267578125,
  221.3000030517578,
  28321200),
 ('AMZN',
  datetime.date(2024, 12, 31),
  222.97000122070312,
  223.22999572753906,
  218.94000244140625,
  219.38999938964844,
  24819700),
 ('AMZN',
  datetime.date(2025, 1, 2),
  222.02999877929688,
  225.14999389648438,
  218.19000244140625,
  220.22000122070312,
  33956600),
 ('AMZN',
  datetime.date(2025, 1, 3),
  222.50999450683594,
  225.36000061035156,
  221.6199951171875,
  224.19000244140625,
  27515600),
 ('AMZN',
  datetime.date(2025, 1, 6),
  226.77999877929688,
  228.83999633789062,
  224.83999633789062,
  227.61000061035156,
  31849800),
 ('AMZN',
  datetime.date(2025, 1, 7),
  227.89999389648438,
  228.3800048828125,
  221.4600067138672,
  222.11000061035156,
  28084200),
 ('AMZN',
  datetime.date(2025, 1, 8),
  223.19000244140625,
  223.52000427246094,
  220.1999969482422,
  222.1300048828125,
  25033300),
 ('AMZN',
  datetime.date(2025, 1, 10),
  221.4600067138672,
  221.7100067138672,
  216.5,
  218.94000244140625,
  36811500),
 ('AMZN',
  datetime.date(2025, 1, 13),
  218.05999755859375,
  219.39999389648438,
  216.47000122070312,
  218.4600067138672,
  27262700),
 ('AMZN',
  datetime.date(2025, 1, 14),
  220.44000244140625,
  221.82000732421875,
  216.1999969482422,
  217.75999450683594,
  24711700),
 ('AMZN',
  datetime.date(2025, 1, 15),
  222.8300018310547,
  223.57000732421875,
  220.75,
  223.35000610351562,
  31291300),
 ('AMZN',
  datetime.date(2025, 1, 16),
  224.4199981689453,
  224.64999389648438,
  220.30999755859375,
  220.66000366210938,
  24757300),
 ('AMZN',
  datetime.date(2025, 1, 17),
  225.83999633789062,
  226.50999450683594,
  223.0800018310547,
  225.94000244140625,
  42370100),
 ('AMZN',
  datetime.date(2025, 1, 21),
  228.89999389648438,
  231.77999877929688,
  226.94000244140625,
  230.7100067138672,
  39951500),
 ('AMZN',
  datetime.date(2025, 1, 22),
  232.02000427246094,
  235.44000244140625,
  231.19000244140625,
  235.00999450683594,
  41448200),
 ('AMZN',
  datetime.date(2025, 1, 23),
  234.10000610351562,
  235.52000427246094,
  231.50999450683594,
  235.4199981689453,
  26404400),
 ('AMZN',
  datetime.date(2025, 1, 24),
  234.5,
  236.39999389648438,
  232.92999267578125,
  234.85000610351562,
  25890700),
 ('AMZN',
  datetime.date(2025, 1, 27),
  226.2100067138672,
  235.61000061035156,
  225.86000061035156,
  235.4199981689453,
  49428300),
 ('AMZN',
  datetime.date(2025, 1, 28),
  234.2899932861328,
  241.77000427246094,
  233.97999572753906,
  238.14999389648438,
  41587200),
 ('AMZN',
  datetime.date(2025, 1, 29),
  239.02000427246094,
  240.38999938964844,
  236.14999389648438,
  237.07000732421875,
  26091700),
 ('AMZN',
  datetime.date(2025, 1, 30),
  237.13999938964844,
  237.9499969482422,
  232.22000122070312,
  234.63999938964844,
  32020700),
 ('AMZN',
  datetime.date(2025, 1, 31),
  236.5,
  240.2899932861328,
  236.41000366210938,
  237.67999267578125,
  36110200),
 ('AMZN',
  datetime.date(2025, 2, 3),
  234.05999755859375,
  239.25,
  232.89999389648438,
  237.4199981689453,
  37285900),
 ('AMZN',
  datetime.date(2025, 2, 4),
  239.00999450683594,
  242.52000427246094,
  238.02999877929688,
  242.05999755859375,
  29713800),
 ('AMZN',
  datetime.date(2025, 2, 5),
  237.02000427246094,
  238.32000732421875,
  235.1999969482422,
  236.1699981689453,
  38727300),
 ('AMZN',
  datetime.date(2025, 2, 6),
  238.00999450683594,
  239.66000366210938,
  236.00999450683594,
  238.8300018310547,
  60897100),
 ('AMZN',
  datetime.date(2025, 2, 7),
  232.5,
  234.80999755859375,
  228.05999755859375,
  229.14999389648438,
  77539300),
 ('AMZN',
  datetime.date(2025, 2, 10),
  230.5500030517578,
  233.9199981689453,
  229.1999969482422,
  233.13999938964844,
  35419900),
 ('AMZN',
  datetime.date(2025, 2, 11),
  231.9199981689453,
  233.44000244140625,
  230.1300048828125,
  232.75999450683594,
  23713700),
 ('AMZN',
  datetime.date(2025, 2, 12),
  230.4600067138672,
  231.17999267578125,
  228.16000366210938,
  228.92999267578125,
  32285200),
 ('AMZN',
  datetime.date(2025, 2, 13),
  228.85000610351562,
  230.4199981689453,
  227.52000427246094,
  230.3699951171875,
  31346500),
 ('AMZN',
  datetime.date(2025, 2, 14),
  229.1999969482422,
  229.88999938964844,
  227.22999572753906,
  228.67999267578125,
  27031100),
 ('AMZN',
  datetime.date(2025, 2, 18),
  228.82000732421875,
  229.3000030517578,
  223.72000122070312,
  226.64999389648438,
  42975100),
 ('AMZN',
  datetime.date(2025, 2, 19),
  225.52000427246094,
  226.8300018310547,
  223.7100067138672,
  226.6300048828125,
  28566700),
 ('AMZN',
  datetime.date(2025, 2, 20),
  224.77999877929688,
  225.1300048828125,
  221.80999755859375,

In [8]:
stockdf

,0,1,2,3,4,5,6
0,AMZN,2024-07-22,185.000000,185.059998,182.479996,182.550003,39931900
1,AMZN,2024-07-23,184.100006,189.389999,183.559998,186.410004,47537700
2,AMZN,2024-07-24,183.199997,185.449997,180.410004,180.830002,41532400
3,AMZN,2024-07-25,182.910004,183.899994,176.800003,179.850006,44464200
4,AMZN,2024-07-26,180.389999,183.190002,180.240005,182.500000,29506000
...,...,...,...,...,...,...,...
1117,AAPG,2025-07-15,38.220001,38.220001,36.759998,36.759998,12500
1118,AAPG,2025-07-16,36.919998,40.009998,36.919998,38.619999,12400
1119,AAPG,2025-07-17,39.000000,39.664001,39.000000,39.619999,5800
1120,AAPG,2025-07-18,40.004002,41.380001,40.004002,40.389999,7100
1121,AAPG,2025-07-21,40.180000,40.320000,39.650002,39.738400,3034

In [12]:
"""활성 심볼 목록 조회"""
con = duckdb.connect(database=db_path, read_only=True)

result = con.execute("""
    SELECT symbol FROM nasdaq_symbols
""").fetchall()
[row[0] for row in result]
con.close()

In [14]:
[row[0] for row in result]

['AAPL',
 'MSFT',
 'GOOGL',
 'AMZN',
 'TSLA',
 'A',
 'AA',
 'AAL',
 'AAMI',
 'AAOI',
 'AAON',
 'AAP',
 'AAPG',
 'AAT',
 'AAUC',
 'AB',
 'ABBV',
 'ABCB',
 'ABCL',
 'ABEV',
 'ABG',
 'ABLLL',
 'ABM',
 'ABNB',
 'ABR',
 'ABT',
 'ACA',
 'ACAD',
 'ACDC',
 'ACEL',
 'ACGL',
 'ACGLN',
 'ACGLO',
 'ACHC',
 'ACHR',
 'ACI',
 'ACIW',
 'ACLS',
 'ACLX',
 'ACM',
 'ACMR',
 'ACN',
 'ACT',
 'ACVA',
 'ADBE',
 'ADC',
 'ADEA',
 'ADI',
 'ADM',
 'ADMA',
 'ADNT',
 'ADP',
 'ADPT',
 'ADSK',
 'ADT',
 'ADUS',
 'AEE',
 'AEG',
 'AEIS',
 'AEM',
 'AEO',
 'AEP',
 'AER',
 'AES',
 'AESI',
 'AEVA',
 'AFG',
 'AFGB',
 'AFGC',
 'AFGD',
 'AFGE',
 'AFL',
 'AFRM',
 'AFYA',
 'AG',
 'AGCO',
 'AGI',
 'AGIO',
 'AGM',
 'AGNC',
 'AGNCL',
 'AGNCM',
 'AGNCN',
 'AGNCO',
 'AGNCP',
 'AGO',
 'AGX',
 'AGYS',
 'AHCO',
 'AHL',
 'AHR',
 'AI',
 'AIG',
 'AIN',
 'AIR',
 'AIT',
 'AIV',
 'AIZ',
 'AIZN',
 'AJG',
 'AKAM',
 'AKBA',
 'AKR',
 'AKRO',
 'AL',
 'ALAB',
 'ALB',
 'ALC',
 'ALE',
 'ALEX',
 'ALG',
 'ALGM',
 'ALGN',
 'ALHC',
 'ALIT',
 'ALK',
 'ALKS',
 'ALKT',
 'ALL',
 'ALLE',
 'ALLY',
 'ALNY',
 'ALRM',
 'ALSN',
 'ALV',
 'ALVO',
 'ALX',
 'AM',
 'AMAL',
 'AMAT',
 'AMBA',
 'AMBP',
 'AMC',
 'AMCR',
 'AMD',
 'AME',
 'AMED',
 'AMG',
 'AMGN',
 'AMH',
 'AMKR',
 'AMP',
 'AMPL',
 'AMPX',
 'AMR',
 'AMRX',
 'AMSC',
 'AMT',
 'AMTM',
 'AMX',
 'AN',
 'ANDE',
 'ANET',
 'ANF',
 'ANIP',
 'AON',
 'AORT',
 'AOS',
 'APA',
 'APAM',
 'APD',
 'APG',
 'APGE',
 'APH',
 'APLD',
 'APLE',
 'APLS',
 'APO',
 'APOS',
 'APP',
 'APPF',
 'APPN',
 'APTV',
 'AQN',
 'AQNB',
 'AR',
 'ARBKL',
 'ARCB',
 'ARCC',
 'ARCO',
 'ARDT',
 'ARDX',
 'ARE',
 'ARES',
 'ARGX',
 'ARHS',
 'ARI',
 'ARIS',
 'ARLO',
 'ARLP',
 'ARM',
 'ARMK',
 'ARMN',
 'AROC',
 'ARQT',
 'ARR',
 'ARRY',
 'ARW',
 'ARWR',
 'AS',
 'ASAN',
 'ASB',
 'ASBA',
 'ASGN',
 'ASH',
 'ASML',
 'ASND',
 'ASO',
 'ASR',
 'ASTH',
 'ASTS',
 'ASX',
 'ATAT',
 'ATEC',
 'ATEN',
 'ATGE',
 'ATHM',
 'ATHS',
 'ATI',
 'ATKR',
 'ATMU',
 'ATO',
 'ATR',
 'ATRC',
 'ATRO',
 'ATS',
 'ATUS',
 'AU',
 'AUB',
 'AUGO',
 'AUPH',
 'AUR',
 'AUROW',
 'AVA',
 'AVAL',
 'AVAV',
 'AVB',
 'AVDL',
 'AVDX',
 'AVGO',
 'AVNT',
 'AVPT',
 'AVT',
 'AVTR',
 'AVY',
 'AWI',
 'AWK',
 'AWR',
 'AX',
 'AXON',
 'AXP',
 'AXS',
 'AXSM',
 'AXTA',
 'AYI',
 'AZN',
 'AZO',
 'AZTA',
 'AZZ',
 'B',
 'BA',
 'BABA',
 'BAC',
 'BAH',
 'BAK',
 'BALL',
 'BAM',
 'BANC',
 'BANF',
 'BANR',
 'BAP',
 'BASE',
 'BATRA',
 'BATRK',
 'BAX',
 'BB',
 'BBAI',
 'BBAR',
 'BBD',
 'BBDC',
 'BBDO',
 'BBIO',
 'BBSI',
 'BBU',
 'BBUC',
 'BBVA',
 'BBWI',
 'BBY',
 'BC',
 'BCAT',
 'BCC',
 'BCE',
 'BCH',
 'BCO',
 'BCPC',
 'BCRX',
 'BCS',
 'BCSF',
 'BDC',
 'BDJ',
 'BDX',
 'BE',
 'BEAM',
 'BEKE',
 'BELFA',
 'BELFB',
 'BEN',
 'BEP',
 'BEPC',
 'BEPH',
 'BEPI',
 'BEPJ',
 'BFAM',
 'BFC',
 'BFH',
 'BG',
 'BGC',
 'BGM',
 'BGR',
 'BHC',
 'BHE',
 'BHF',
 'BHFAL',
 'BHFAO',
 'BHLB',
 'BHP',
 'BHVN',
 'BIDU',
 'BIIB',
 'BILI',
 'BILL',
 'BIO',
 'BIP',
 'BIPC',
 'BIPH',
 'BIPJ',
 'BIRK',
 'BJ',
 'BK',
 'BKD',
 'BKE',
 'BKH',
 'BKNG',
 'BKR',
 'BKT',
 'BKU',
 'BKV',
 'BL',
 'BLBD',
 'BLCO',
 'BLD',
 'BLDR',
 'BLK',
 'BLKB',
 'BLTE',
 'BLX',
 'BMA',
 'BMI',
 'BMO',
 'BMRN',
 'BMY',
 'BN',
 'BNH',
 'BNJ',
 'BNL',
 'BNS',
 'BNT',
 'BNTX',
 'BOH',
 'BOKF',
 'BOOT',
 'BOW',
 'BOX',
 'BP',
 'BPMC',
 'BPOP',
 'BPOPM',
 'BPYPM',
 'BPYPN',
 'BPYPO',
 'BPYPP',
 'BR',
 'BRBR',
 'BRC',
 'BRDG',
 'BRFS',
 'BRK/A',
 'BRK/B',
 'BRKR',
 'BRO',
 'BROS',
 'BRSL',
 'BRX',
 'BRZE',
 'BSAC',
 'BSBR',
 'BSM',
 'BSX',
 'BSY',
 'BTDR',
 'BTE',
 'BTG',
 'BTI',
 'BTSG',
 'BTSGU',
 'BTU',
 'BTX',
 'BTZ',
 'BUD',
 'BULL',
 'BULLW',
 'BUR',
 'BURL',
 'BUSE',
 'BUSEP',
 'BV',
 'BVN',
 'BWA',
 'BWIN',
 'BWLP',
 'BWNB',
 'BWSN',
 'BWXT',
 'BX',
 'BXMT',
 'BXP',
 'BY',
 'BYD',
 'BZ',
 'C',
 'CAAP',
 'CACC',
 'CACI',
 'CADE',
 'CAE',
 'CAG',
 'CAH',
 'CAI',
 'CAKE',
 'CALM',
 'CALX',
 'CAMT',
 'CAR',
 'CARG',
 'CARR',
 'CART',
 'CASH',
 'CASY',
 'CAT',
 'CATY',
 'CAVA',
 'CB',
 'CBOE',
 'CBRE',
 'CBRL',
 'CBSH',
 'CBT',
 'CBU',
 'CBZ',
 'CC',
 'CCB',
 'CCCS',
 'CCEC',
 'CCEP',
 'CCI',
 'CCJ',
 'CCK',
 'CCL',
 'CCOI',
 'CCS',
 'CCZ',
 'CDE',
 'CDLR',
 'CDNS',
 'CDP',
 'CDRE',
 'CDW',
 'CDZIP',
 'CE',
 'CECO',
 'CEG',
 'CELH',
 'CENT',
 'CENTA',
 'CENX',
 'CEPU',
 'CERT',
 'CET',
 'CF',
 'CFG',
 'CFLT',
 'CFR',
 'CG',
 'CGABL',
 'CGAU',
 'CGBD',
 'CGBDL',
 'CGNX',
 'CGON',
 'CHA',
 'CHCO',
 'CHD',
 'CHDN',
 'CHE',
 'CHEF',
 'CHH',
 'CHKP',
 'CHRD',
 'CHRW',
 'CHT',
 'CHTR',
 'CHWY',
 'CHYM',
 'CI',
 'CIB',
 'CIEN',
 'CIFR',
 'CIG',
 'CIGI',
 'CII',
 'CIM',
 'CIMN',
 'CINF',
 'CIVI',
 'CL',
 'CLBK',
 'CLBT',
 'CLDX',
 'CLF',
 'CLH',
 'CLMT',
 'CLOV',
 'CLS',
 'CLSK',
 'CLVT',
 'CLX',
 'CM',
 'CMA',
 'CMBT',
 'CMC',
 'CMCM',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMPO',
 'CMPR',
 'CMRE',
 'CMS',
 'CMSA',
 'CMSC',
 'CMSD',
 'CNA',
 'CNC',
 'CNH',
 'CNI',
 'CNK',
 'CNM',
 'CNMD',
 'CNNE',
 'CNO',
 'CNP',
 'CNQ',
 'CNR',
 'CNS',
 'CNTA',
 'CNX',
 'CNXC',
 'CNXN',
 'COCO',
 'COF',
 'COGT',
 'COHR',
 'COIN',
 'COKE',
 'COLB',
 'COLD',
 'COLL',
 'COLM',
 'COMM',
 'COMP',
 'CON',
 'COO',
 'COOP',
 'COP',
 'COR',
 'CORT',
 'CORZ',
 'CORZW',
 'CORZZ',
 'COST',
 'COTY',
 'COUR',
 'CP',
 'CPA',
 'CPAY',
 'CPB',
 'CPK',
 'CPNG',
 'CPRI',
 'CPRT',
 'CPRX',
 'CPT',
 'CQP',
 'CR',
 'CRAI',
 'CRBG',
 'CRC',
 'CRCL',
 'CRCT',
 'CRDO',
 'CRGY',
 'CRH',
 'CRI',
 'CRK',
 'CRL',
 'CRM',
 'CRNX',
 'CROX',
 'CRS',
 'CRSP',
 'CRTO',
 'CRUS',
 'CRVL',
 'CRWD',
 'CRWV',
 'CSAN',
 'CSCO',
 'CSGP',
 'CSGS',
 'CSL',
 'CSQ',
 'CSTM',
 'CSW',
 'CSWC',
 'CSWCZ',
 'CSX',
 'CTAS',
 'CTBI',
 'CTOS',
 'CTRA',
 'CTRE',
 'CTRI',
 'CTS',
 'CTSH',
 'CTVA',
 'CUBE',
 'CUBI',
 'CUK',
 'CURB',
 'CUZ',
 'CVAC',
 'CVBF',
 'CVCO',
 'CVE',
 'CVI',
 'CVLT',
 'CVNA',
 'CVS',
 'CVX',
 'CW',
 'CWAN',
 'CWEN',
 'CWH',
 'CWK',
 'CWST',
 'CWT',
 'CX',
 'CXM',
 'CXT',
 'CXW',
 'CYBR',
 'CYTK',
 'CZR',
 'D',
 'DAC',
 'DAL',
 'DAN',
 'DAO',
 'DAR',
 'DASH',
 'DAVE',
 'DAY',
 'DB',
 'DBD',
 'DBRG',
 'DBX',
 'DCI',
 'DCO',
 'DCOM',
 'DCOMG',
 'DD',
 'DDOG',
 'DDS',
 'DE',
 'DEA',
 'DECK',
 'DEFT',
 'DEI',
 'DELL',
 'DEO',
 'DFH',
 'DFIN',
 'DG',
 'DGII',
 'DGNX',
 'DGX',
 'DHCNI',
 'DHCNL',
 'DHI',
 'DHR',
 'DHT',
 'DINO',
 'DIOD',
 'DIS',
 'DJT',
 'DJTWW',
 'DK',
 'DKL',
 'DKNG',
 'DKS',
 'DLB',
 'DLO',
 'DLR',
 'DLTR',
 'DMLP',
 'DNB',
 'DNLI',
 'DNN',
 'DNOW',
 'DOC',
 'DOCN',
 'DOCS',
 'DOCU',
 'DOLE',
 'DOOO',
 'DORM',
 'DOV',
 'DOW',
 'DOX',
 'DPZ',
 'DQ',
 'DRD',
 'DRH',
 'DRI',
 'DRS',
 'DRVN',
 'DSGR',
 'DSGX',
 'DSL',
 'DT',
 'DTB',
 'DTE',
 'DTG',
 'DTM',
 'DTW',
 'DUK',
 'DUKB',
 'DUOL',
 'DV',
 'DVA',
 'DVAX',
 'DVN',
 'DX',
 'DXC',
 'DXCM',
 'DXPE',
 'DY',
 'DYN',
 'E',
 'EA',
 'EAI',
 'EAT',
 'EBAY',
 'EBC',
 'EBR',
 'EC',
 'ECAT',
 'ECCC',
 'ECCF',
 'ECCV',
 'ECCW',
 'ECCX',
 'ECG',
 'ECL',
 'ECVT',
 'ED',
 'EDN',
 'EDU',
 'EE',
 'EEFT',
 'EFC',
 'EFSC',
 'EFX',
 'EG',
 'EH',
 'EHC',
 'EIG',
 'EIX',
 'EL',
 'ELAN',
 'ELC',
 'ELF',
 'ELME',
 'ELP',
 'ELPC',
 'ELS',
 'ELV',
 'ELVN',
 'EMA',
 'EME',
 'EMN',
 'EMP',
 'EMR',
 'ENB',
 'ENIC',
 'ENJ',
 'ENLT',
 'ENO',
 'ENOV',
 'ENPH',
 'ENR',
 'ENS',
 'ENSG',
 'ENTG',
 'ENVA',
 'ENVX',
 'EOG',
 'EOSE',
 'EPAC',
 'EPAM',
 'EPC',
 'EPD',
 'EPR',
 'EPRT',
 'EQH',
 'EQIX',
 'EQNR',
 'EQR',
 'EQT',
 'EQX',
 'ERIC',
 'ERIE',
 'ERJ',
 'ERO',
 'ES',
 'ESAB',
 'ESE',
 'ESI',
 'ESLT',
 'ESNT',
 'ESRT',
 'ESS',
 'ESTA',
 'ESTC',
 'ET',
 'ETN',
 'ETNB',
 'ETOR',
 'ETR',
 'ETSY',
 'ETV',
 'ETWO',
 'EVCM',
 'EVEX',
 'EVGO',
 'EVH',
 'EVR',
 'EVRG',
 'EVTC',
 'EW',
 'EWBC',
 'EWTX',
 'EXAS',
 'EXC',
 'EXE',
 'EXEEL',
 'EXEL',
 'EXK',
 'EXLS',
 'EXOD',
 'EXP',
 'EXPD',
 'EXPE',
 'EXPI',
 'EXPO',
 'EXR',
 'EXTR',
 'EYE',
 'F',
 'FA',
 'FAF',
 'FANG',
 'FAST',
 'FBIN',
 'FBK',
 'FBNC',
 'FBP',
 'FCF',
 'FCFS',
 'FCN',
 'FCNCA',
 'FCPT',
 'FCX',
 'FDP',
 'FDS',
 'FDX',
 'FE',
 'FELE',
 'FER',
 'FERG',
 'FFBC',
 'FFIN',
 'FFIV',
 'FG',
 'FGN',
 'FHB',
 'FHI',
 'FHN',
 'FI',
 'FIBK',
 'FICO',
 'FIHL',
 'FINV',
 'FIS',
 'FITB',
 'FITBI',
 'FITBO',
 'FITBP',
 'FIVE',
 'FIVN',
 'FIX',
 'FIZZ',
 'FL',
 'FLEX',
 'FLG',
 'FLNC',
 'FLNG',
 'FLO',
 'FLOC',
 'FLR',
 'FLS',
 'FLUT',
 'FLYW',
 'FMC',
 'FMS',
 'FMX',
 'FN',
 'FNB',
 'FND',
 'FNF',
 'FNV',
 'FOLD',
 'FOR',
 'FORM',
 'FORTY',
 'FOUR',
 'FOX',
 'FOXA',
 'FOXF',
 'FR',
 'FRA',
 'FRHC',
 'FRME',
 'FRMEP',
 'FRO',
 'FROG',
 'FRPT',
 'FRSH',
 'FRT',
 'FSCO',
 'FSK',
 'FSLR',
 'FSLY',
 'FSM',
 'FSS',
 'FSUN',
 'FSV',
 'FTAI',
 'FTAIM',
 'FTAIN',
 'FTDR',
 'FTI',
 'FTNT',
 'FTS',
 'FTV',
 'FUBO',
 'FUL',
 'FULT',
 'FULTP',
 'FUN',
 'FUTU',
 'FWONA',
 'FWONK',
 'FWRG',
 'FYBR',
 'G',
 'GAB',
 'GABC',
 'GAM',
 ...]

In [4]:
# watchlist 테이블 확인
con = duckdb.connect(database=db_path, read_only=True)

try:
    # watchlist 테이블 존재 확인
    watchlist_result = con.execute("SELECT COUNT(*) FROM watchlist").fetchall()
    print(f"watchlist 테이블 레코드 수: {watchlist_result[0][0]}")
    
    # 활성 watchlist 확인
    active_watchlist = con.execute("""
        SELECT DISTINCT symbol 
        FROM watchlist 
        WHERE is_active = true 
        ORDER BY symbol
    """).fetchall()
    
    print(f"활성화된 watchlist 종목 수: {len(active_watchlist)}")
    if active_watchlist:
        print("활성 종목들:", [row[0] for row in active_watchlist[:10]])  # 처음 10개만 출력
        
except Exception as e:
    print(f"watchlist 테이블 조회 오류: {e}")
    print("watchlist 테이블이 존재하지 않거나 접근할 수 없습니다.")

con.close()

IOException: IO Error: Could not set lock on file "/home/grey1/stock-kafka3/data/duckdb/stock_data.db": Conflicting lock is held in airflow task runner: nasdaq_daily_pipeline collect_nasdaq_symbols manual__2025-07-24T12:56:49.635923+00:00 92 (PID 1702482). See also https://duckdb.org/docs/stable/connect/concurrency

In [5]:
# daily_watchlist 테이블 구조 확인
con = duckdb.connect(database=db_path, read_only=True)

try:
    # 테이블 존재 확인
    tables = con.execute("SHOW TABLES").fetchall()
    print("데이터베이스 테이블들:", [table[0] for table in tables])
    
    # daily_watchlist 테이블이 있는지 확인
    if ('daily_watchlist',) in tables:
        # 테이블 구조 확인
        table_info = con.execute("PRAGMA table_info('daily_watchlist')").fetchall()
        print("\ndaily_watchlist 테이블 구조:")
        for col in table_info:
            print(f"  {col[1]} {col[2]} (NOT NULL: {col[3]}, PK: {col[5]})")
            
        # 데이터 확인
        count = con.execute("SELECT COUNT(*) FROM daily_watchlist").fetchall()[0][0]
        print(f"\ndaily_watchlist 레코드 수: {count}")
        
        if count > 0:
            sample = con.execute("SELECT * FROM daily_watchlist LIMIT 3").fetchall()
            print("샘플 데이터:", sample)
    else:
        print("\ndaily_watchlist 테이블이 존재하지 않습니다.")
        
except Exception as e:
    print(f"daily_watchlist 테이블 조회 오류: {e}")

con.close()

데이터베이스 테이블들: ['daily_watchlist', 'nasdaq_symbols', 'stock_data', 'stock_data_technical_indicators', 'stock_technical_indicators', 'watchlist']

daily_watchlist 테이블 구조:
  id INTEGER (NOT NULL: True, PK: True)
  symbol VARCHAR (NOT NULL: True, PK: False)
  date DATE (NOT NULL: True, PK: False)
  condition_type VARCHAR (NOT NULL: True, PK: False)
  condition_value DECIMAL(10,4) (NOT NULL: False, PK: False)
  market_cap_tier INTEGER (NOT NULL: False, PK: False)
  created_at TIMESTAMP (NOT NULL: False, PK: False)

daily_watchlist 레코드 수: 0

In [7]:
# daily_watchlist 테이블을 자동 증가 ID로 재생성 (DuckDB 방식)
con = duckdb.connect(database=db_path, read_only=False)

try:
    # 기존 테이블 백업 (데이터가 있다면)
    try:
        backup_count = con.execute("SELECT COUNT(*) FROM daily_watchlist").fetchall()[0][0]
        print(f"기존 데이터 수: {backup_count}")
    except:
        backup_count = 0
        print("기존 테이블이 없거나 삭제됨")
    
    # 시퀀스 생성 (DuckDB의 자동 증가 방식)
    try:
        con.execute("DROP SEQUENCE IF EXISTS daily_watchlist_id_seq")
    except:
        pass
        
    con.execute("CREATE SEQUENCE daily_watchlist_id_seq START 1")
    print("시퀀스 생성 완료")
    
    # 기존 테이블 삭제
    con.execute("DROP TABLE IF EXISTS daily_watchlist")
    print("기존 테이블 삭제 완료")
    
    # 새 테이블 생성 (시퀀스 사용)
    con.execute("""
        CREATE TABLE daily_watchlist (
            id INTEGER PRIMARY KEY DEFAULT nextval('daily_watchlist_id_seq'),
            symbol VARCHAR NOT NULL,
            date DATE NOT NULL,
            condition_type VARCHAR NOT NULL,
            condition_value DECIMAL(10,4),
            market_cap_tier INTEGER,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(symbol, date, condition_type)  -- 중복 방지
        )
    """)
    print("새 테이블 생성 완료 (자동 증가 ID 포함)")
    
    # 테스트 데이터 삽입 (ID 없이)
    con.execute("""
        INSERT INTO daily_watchlist (symbol, date, condition_type, condition_value, market_cap_tier)
        VALUES ('AAPL', '2025-07-25', 'bollinger_upper_touch', 0.985, 1)
    """)
    
    # 결과 확인
    result = con.execute("SELECT * FROM daily_watchlist").fetchall()
    print(f"테스트 삽입 결과: {result}")
    
    # 새 테이블 구조 확인
    table_info = con.execute("PRAGMA table_info('daily_watchlist')").fetchall()
    print("\n새 테이블 구조:")
    for col in table_info:
        print(f"  {col[1]} {col[2]} (NOT NULL: {col[3]}, PK: {col[5]})")
        
    print("\n✅ 테이블 재생성 완료! (자동 ID 생성)")
    
except Exception as e:
    print(f"❌ 테이블 재생성 실패: {e}")

con.close()

기존 테이블이 없거나 삭제됨
시퀀스 생성 완료
기존 테이블 삭제 완료
새 테이블 생성 완료 (자동 증가 ID 포함)
테스트 삽입 결과: [(1, 'AAPL', datetime.date(2025, 7, 25), 'bollinger_upper_touch', Decimal('0.9850'), 1, datetime.datetime(2025, 7, 26, 17, 46, 49, 272000))]

새 테이블 구조:
  id INTEGER (NOT NULL: True, PK: True)
  symbol VARCHAR (NOT NULL: True, PK: False)
  date DATE (NOT NULL: True, PK: False)
  condition_type VARCHAR (NOT NULL: True, PK: False)
  condition_value DECIMAL(10,4) (NOT NULL: False, PK: False)
  market_cap_tier INTEGER (NOT NULL: False, PK: False)
  created_at TIMESTAMP (NOT NULL: False, PK: False)

✅ 테이블 재생성 완료! (자동 ID 생성)

In [8]:
# 데이터베이스 파일 상태 확인 및 복구
import os
import duckdb

db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'
replica_db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data_replica.db'

print("🔍 데이터베이스 상태 진단...")

# 1. 파일 크기 및 존재 확인
print(f"Main DB 존재: {os.path.exists(db_path)}")
if os.path.exists(db_path):
    size_mb = os.path.getsize(db_path) / (1024 * 1024)
    print(f"Main DB 크기: {size_mb:.2f} MB")

print(f"Replica DB 존재: {os.path.exists(replica_db_path)}")
if os.path.exists(replica_db_path):
    size_mb = os.path.getsize(replica_db_path) / (1024 * 1024)
    print(f"Replica DB 크기: {size_mb:.2f} MB")

# 2. 데이터베이스 연결 테스트
print("\n🔧 데이터베이스 연결 테스트...")
try:
    con = duckdb.connect(database=db_path, read_only=True)
    print("✅ Main DB 연결 성공")
    
    # 기본 테이블 확인
    tables = con.execute("SHOW TABLES").fetchall()
    print(f"테이블 수: {len(tables)}")
    print("테이블 목록:", [t[0] for t in tables])
    
    con.close()
    
except Exception as e:
    print(f"❌ Main DB 연결 실패: {e}")
    print("데이터베이스 파일이 손상되었을 가능성이 있습니다.")
    
    # Replica DB로 복구 시도
    if os.path.exists(replica_db_path):
        print("\n🔄 Replica DB로 복구 시도...")
        try:
            con_replica = duckdb.connect(database=replica_db_path, read_only=True)
            tables = con_replica.execute("SHOW TABLES").fetchall()
            print(f"✅ Replica DB 연결 성공, 테이블 수: {len(tables)}")
            con_replica.close()
            
            # Main DB 백업 후 Replica로 교체
            backup_path = db_path + '.backup.' + str(int(time.time()))
            print(f"Main DB를 {backup_path}로 백업...")
            os.rename(db_path, backup_path)
            
            print(f"Replica DB를 Main DB로 복사...")
            import shutil
            shutil.copy2(replica_db_path, db_path)
            print("✅ 데이터베이스 복구 완료")
            
        except Exception as replica_error:
            print(f"❌ Replica DB도 손상됨: {replica_error}")
        
except Exception as e:
    print(f"❌ 예상치 못한 오류: {e}")

🔍 데이터베이스 상태 진단...
Main DB 존재: True
Main DB 크기: 3.76 MB
Replica DB 존재: True
Replica DB 크기: 3.76 MB

🔧 데이터베이스 연결 테스트...
✅ Main DB 연결 성공
테이블 수: 6
테이블 목록: ['daily_watchlist', 'nasdaq_symbols', 'stock_data', 'stock_data_technical_indicators', 'stock_technical_indicators', 'watchlist']

In [9]:
# Airflow 컨테이너 경로로 데이터베이스 접근 테스트
airflow_db_path = '/data/duckdb/stock_data.db'

print("🐳 Airflow 컨테이너 경로 테스트...")
print(f"경로: {airflow_db_path}")
print(f"파일 존재: {os.path.exists(airflow_db_path)}")

if os.path.exists(airflow_db_path):
    try:
        size_mb = os.path.getsize(airflow_db_path) / (1024 * 1024)
        print(f"파일 크기: {size_mb:.2f} MB")
        
        # 연결 테스트
        con = duckdb.connect(database=airflow_db_path, read_only=True)
        tables = con.execute("SHOW TABLES").fetchall()
        print(f"✅ Airflow 경로 연결 성공, 테이블 수: {len(tables)}")
        
        # daily_watchlist 테이블 구조 확인
        if ('daily_watchlist',) in tables:
            table_info = con.execute("PRAGMA table_info('daily_watchlist')").fetchall()
            print("\nAirflow 경로의 daily_watchlist 구조:")
            for col in table_info:
                print(f"  {col[1]} {col[2]} (NOT NULL: {col[3]}, PK: {col[5]})")
        
        con.close()
        
    except Exception as e:
        print(f"❌ Airflow 경로 연결 실패: {e}")
        
        # 파일이 존재하지만 연결 실패하는 경우 - 파일 손상 가능성
        if "Serialization Error" in str(e):
            print("🚨 직렬화 오류 감지 - 데이터베이스 파일 재생성 필요")
            
            # 안전한 데이터베이스 재생성
            print("🔄 새로운 데이터베이스 파일 생성...")
            backup_path = airflow_db_path + '.corrupted.' + str(int(time.time()))
            
            try:
                import shutil
                shutil.move(airflow_db_path, backup_path)
                print(f"손상된 파일을 {backup_path}로 이동")
                
                # 로컬 DB에서 복사
                local_db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'
                shutil.copy2(local_db_path, airflow_db_path)
                print(f"로컬 DB를 {airflow_db_path}로 복사 완료")
                
                # 새 파일 연결 테스트
                con = duckdb.connect(database=airflow_db_path, read_only=True)
                tables = con.execute("SHOW TABLES").fetchall()
                print(f"✅ 복구된 DB 연결 성공, 테이블 수: {len(tables)}")
                con.close()
                
            except Exception as recovery_error:
                print(f"❌ 복구 실패: {recovery_error}")
        
else:
    print("❌ Airflow 경로에 데이터베이스 파일이 없습니다.")
    print("Docker 볼륨 마운트 확인이 필요합니다.")

🐳 Airflow 컨테이너 경로 테스트...
경로: /data/duckdb/stock_data.db
파일 존재: False
❌ Airflow 경로에 데이터베이스 파일이 없습니다.
Docker 볼륨 마운트 확인이 필요합니다.

In [10]:
# 다른 DAG vs daily_watchlist_scanner 차이점 분석
print("🔍 DAG별 데이터베이스 접근 패턴 분석...")

# 1. 다른 DAG들이 사용하는 경로들 확인
possible_paths = [
    '/home/grey1/stock-kafka3/data/duckdb/stock_data.db',  # 로컬 경로
    '/data/duckdb/stock_data.db',  # Airflow 컨테이너 경로
    '/opt/airflow/data/duckdb/stock_data.db',  # 다른 컨테이너 경로
    './data/duckdb/stock_data.db',  # 상대 경로
]

print("경로별 파일 존재 여부:")
for path in possible_paths:
    exists = os.path.exists(path)
    if exists:
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"✅ {path} - {size_mb:.2f} MB")
    else:
        print(f"❌ {path} - 없음")

print("\n🤔 추정되는 이유들:")
print("1. 다른 DAG들은 로컬 경로(/home/grey1/...)를 사용할 수 있음")
print("2. daily_watchlist_scanner만 TechnicalScanner 클래스를 사용함")
print("3. TechnicalScanner → DuckDBManager 초기화에서 경로 문제 발생")
print("4. 다른 DAG들은 직접 DB 연결하거나 다른 클래스 사용")

🔍 DAG별 데이터베이스 접근 패턴 분석...
경로별 파일 존재 여부:
✅ /home/grey1/stock-kafka3/data/duckdb/stock_data.db - 3.76 MB
❌ /data/duckdb/stock_data.db - 없음
❌ /opt/airflow/data/duckdb/stock_data.db - 없음
❌ ./data/duckdb/stock_data.db - 없음

🤔 추정되는 이유들:
1. 다른 DAG들은 로컬 경로(/home/grey1/...)를 사용할 수 있음
2. daily_watchlist_scanner만 TechnicalScanner 클래스를 사용함
3. TechnicalScanner → DuckDBManager 초기화에서 경로 문제 발생
4. 다른 DAG들은 직접 DB 연결하거나 다른 클래스 사용

In [11]:
# DuckDBManager 직접 접근 vs TechnicalScanner 접근 비교 테스트
import sys

# 테스트할 경로들
airflow_path = "/data/duckdb/stock_data.db"
local_path = "/home/grey1/stock-kafka3/data/duckdb/stock_data.db"

print("🧪 접근 방법별 테스트...")

# 1. DuckDB 직접 접근 (nasdaq_daily_pipeline 방식)
print("\n1️⃣ DuckDB 직접 접근 테스트:")
try:
    import duckdb
    con = duckdb.connect(database=airflow_path, read_only=True)
    tables = con.execute("SHOW TABLES").fetchall()
    print(f"✅ DuckDB 직접 접근 성공: {len(tables)}개 테이블")
    con.close()
except Exception as e:
    print(f"❌ DuckDB 직접 접근 실패: {e}")
    
    # 로컬 경로로 다시 시도
    try:
        con = duckdb.connect(database=local_path, read_only=True)
        tables = con.execute("SHOW TABLES").fetchall()
        print(f"✅ 로컬 경로 직접 접근 성공: {len(tables)}개 테이블")
        con.close()
    except Exception as e2:
        print(f"❌ 로컬 경로도 실패: {e2}")

# 2. DuckDBManager 클래스 접근 테스트
print("\n2️⃣ DuckDBManager 클래스 접근 테스트:")
sys.path.insert(0, '/home/grey1/stock-kafka3/common')
try:
    from database import DuckDBManager
    
    # Airflow 경로로 시도
    try:
        db = DuckDBManager(airflow_path, read_only=True)
        print("✅ DuckDBManager Airflow 경로 성공")
        db.conn.close()
    except Exception as e:
        print(f"❌ DuckDBManager Airflow 경로 실패: {e}")
        
        # 로컬 경로로 시도
        try:
            db = DuckDBManager(local_path, read_only=True)
            print("✅ DuckDBManager 로컬 경로 성공")
            db.conn.close()
        except Exception as e2:
            print(f"❌ DuckDBManager 로컬 경로도 실패: {e2}")
            
except ImportError as e:
    print(f"❌ DuckDBManager import 실패: {e}")

# 3. TechnicalScanner 클래스 접근 테스트
print("\n3️⃣ TechnicalScanner 클래스 접근 테스트:")
try:
    from technical_scanner import TechnicalScanner
    
    # Airflow 경로로 시도
    try:
        scanner = TechnicalScanner(db_path=airflow_path)
        print("✅ TechnicalScanner Airflow 경로 성공")
        scanner.db.conn.close()
    except Exception as e:
        print(f"❌ TechnicalScanner Airflow 경로 실패: {e}")
        
        # 로컬 경로로 시도
        try:
            scanner = TechnicalScanner(db_path=local_path)
            print("✅ TechnicalScanner 로컬 경로 성공")
            scanner.db.conn.close()
        except Exception as e2:
            print(f"❌ TechnicalScanner 로컬 경로도 실패: {e2}")
            
except ImportError as e:
    print(f"❌ TechnicalScanner import 실패: {e}")

print("\n🔍 결론:")
print("- nasdaq_daily_pipeline: DuckDBManager 직접 사용")
print("- daily_watchlist_scanner: TechnicalScanner → DuckDBManager 사용")
print("- 문제는 TechnicalScanner 초기화 과정에서 발생할 가능성 높음")

🧪 접근 방법별 테스트...

1️⃣ DuckDB 직접 접근 테스트:
❌ DuckDB 직접 접근 실패: IO Error: Cannot open database "/data/duckdb/stock_data.db" in read-only mode: database does not exist
✅ 로컬 경로 직접 접근 성공: 6개 테이블

2️⃣ DuckDBManager 클래스 접근 테스트:
❌ DuckDBManager Airflow 경로 실패: IO Error: Cannot open database "/data/duckdb/stock_data.db" in read-only mode: database does not exist
⚠️ 지표 설정 파일이 없어 기본 설정을 생성합니다.
✅ DuckDBManager 로컬 경로 성공

3️⃣ TechnicalScanner 클래스 접근 테스트:
✅ TechnicalScanner Airflow 경로 성공

🔍 결론:
- nasdaq_daily_pipeline: DuckDBManager 직접 사용
- daily_watchlist_scanner: TechnicalScanner → DuckDBManager 사용
- 문제는 TechnicalScanner 초기화 과정에서 발생할 가능성 높음

In [3]:
# DuckDB 디렉토리 파일 상태 확인
import os
import glob
from datetime import datetime

duckdb_dir = '/home/grey1/stock-kafka3/data/duckdb'
airflow_duckdb_dir = '/data/duckdb'

print("🗂️ DuckDB 디렉토리 파일 목록 확인...")

# 로컬 디렉토리 확인
print(f"\n📁 로컬 디렉토리: {duckdb_dir}")
if os.path.exists(duckdb_dir):
    files = os.listdir(duckdb_dir)
    print(f"파일 수: {len(files)}")
    
    for file in sorted(files):
        file_path = os.path.join(duckdb_dir, file)
        if os.path.isfile(file_path):
            size_mb = os.path.getsize(file_path) / (1024 * 1024)
            mtime = datetime.fromtimestamp(os.path.getmtime(file_path))
            print(f"  📄 {file} - {size_mb:.2f} MB ({mtime.strftime('%Y-%m-%d %H:%M')})")
else:
    print("❌ 로컬 디렉토리가 존재하지 않습니다")

# Airflow 컨테이너 디렉토리 확인
print(f"\n🐳 Airflow 디렉토리: {airflow_duckdb_dir}")
if os.path.exists(airflow_duckdb_dir):
    files = os.listdir(airflow_duckdb_dir)
    print(f"파일 수: {len(files)}")
    
    for file in sorted(files):
        file_path = os.path.join(airflow_duckdb_dir, file)
        if os.path.isfile(file_path):
            size_mb = os.path.getsize(file_path) / (1024 * 1024)
            mtime = datetime.fromtimestamp(os.path.getmtime(file_path))
            print(f"  📄 {file} - {size_mb:.2f} MB ({mtime.strftime('%Y-%m-%d %H:%M')})")
else:
    print("❌ Airflow 디렉토리가 존재하지 않습니다")

# 백업 파일 패턴 찾기
print("\n🗃️ 백업 파일 분석...")
backup_patterns = [
    "*.backup*",
    "*.corrupted*", 
    "*_backup_*"
]

all_backup_files = []
for directory in [duckdb_dir, airflow_duckdb_dir]:
    if os.path.exists(directory):
        for pattern in backup_patterns:
            backup_files = glob.glob(os.path.join(directory, pattern))
            all_backup_files.extend(backup_files)

if all_backup_files:
    print(f"총 백업 파일 수: {len(all_backup_files)}")
    total_size = 0
    for backup_file in sorted(all_backup_files):
        size_mb = os.path.getsize(backup_file) / (1024 * 1024)
        total_size += size_mb
        mtime = datetime.fromtimestamp(os.path.getmtime(backup_file))
        print(f"  🗃️ {os.path.basename(backup_file)} - {size_mb:.2f} MB ({mtime.strftime('%Y-%m-%d %H:%M')})")
    
    print(f"\n💾 총 백업 파일 크기: {total_size:.2f} MB")
else:
    print("백업 파일이 없습니다.")

🗂️ DuckDB 디렉토리 파일 목록 확인...

📁 로컬 디렉토리: /home/grey1/stock-kafka3/data/duckdb
파일 수: 9
  📄 stock_data.db.backup_20250727_044639 - 3.76 MB (2025-07-26 17:46)
  📄 stock_data.db.backup_20250727_044735 - 0.01 MB (2025-07-27 13:46)
  📄 stock_data.db.backup_20250727_053911 - 1.01 MB (2025-07-27 13:53)
  📄 stock_data.db.backup_20250727_140005 - 2.51 MB (2025-07-27 14:53)
  📄 stock_data.db.backup_20250727_140542 - 0.01 MB (2025-07-27 23:05)
  📄 stock_data.db.backup_20250727_143027 - 0.01 MB (2025-07-27 23:30)
  📄 stock_data.db.backup_20250727_143605 - 0.01 MB (2025-07-27 23:36)
  📄 stock_data.db.wal - 0.00 MB (2025-07-27 23:36)
  📄 stock_data_replica.db - 2.51 MB (2025-07-27 14:53)

🐳 Airflow 디렉토리: /data/duckdb
파일 수: 0

🗃️ 백업 파일 분석...
총 백업 파일 수: 7
  🗃️ stock_data.db.backup_20250727_044639 - 3.76 MB (2025-07-26 17:46)
  🗃️ stock_data.db.backup_20250727_044735 - 0.01 MB (2025-07-27 13:46)
  🗃️ stock_data.db.backup_20250727_053911 - 1.01 MB (2025-07-27 13:53)
  🗃️ stock_data.db.backup_20250727_140005 - 2.51 MB (2025-07-27 14:53)
  🗃️ stock_data.db.backup_20250727_140542 - 0.01 MB (2025-07-27 23:05)
  🗃️ stock_data.db.backup_20250727_143027 - 0.01 MB (2025-07-27 23:30)
  🗃️ stock_data.db.backup_20250727_143605 - 0.01 MB (2025-07-27 23:36)

💾 총 백업 파일 크기: 7.33 MB

In [4]:
# 데이터베이스 복구 및 백업 파일 정리
import shutil
import os
from datetime import datetime

print("🔧 데이터베이스 복구 작업 시작...")

# 1. 가장 큰 백업 파일 (데이터가 있는 파일) 찾기
backup_files = [
    ('/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_044639', 3.76),
    ('/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_140005', 2.51),
    ('/home/grey1/stock-kafka3/data/duckdb/stock_data_replica.db', 2.51)
]

# 가장 큰 파일을 메인 DB로 복구
source_file = backup_files[0][0]  # 3.76MB 파일
main_db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'
airflow_db_path = '/data/duckdb/stock_data.db'

print(f"📦 복구 소스: {os.path.basename(source_file)} ({backup_files[0][1]} MB)")

# 2. 로컬 메인 DB 복구
try:
    shutil.copy2(source_file, main_db_path)
    print(f"✅ 로컬 DB 복구 완료: {main_db_path}")
    
    # 복구된 파일 검증
    import duckdb
    con = duckdb.connect(database=main_db_path, read_only=True)
    tables = con.execute("SHOW TABLES").fetchall()
    print(f"✅ 복구 검증 성공: {len(tables)}개 테이블")
    
    # 테이블별 데이터 개수 확인
    for table in tables:
        table_name = table[0]
        try:
            count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
            print(f"  📊 {table_name}: {count:,}개 레코드")
        except Exception as e:
            print(f"  ❌ {table_name}: 조회 실패 ({e})")
    
    con.close()
    
except Exception as e:
    print(f"❌ 로컬 DB 복구 실패: {e}")

# 3. Airflow 컨테이너용 디렉토리 생성 및 복사
try:
    # 디렉토리 생성
    os.makedirs('/data/duckdb', exist_ok=True)
    
    # 파일 복사
    shutil.copy2(main_db_path, airflow_db_path)
    print(f"✅ Airflow DB 복구 완료: {airflow_db_path}")
    
    # 파일 권한 설정 (Airflow에서 접근 가능하도록)
    os.chmod(airflow_db_path, 0o666)
    print("✅ 파일 권한 설정 완료")
    
except Exception as e:
    print(f"❌ Airflow DB 복구 실패: {e}")

# 4. 오래된 백업 파일들 정리 (크기가 작은 빈 파일들)
print("\n🧹 오래된 백업 파일 정리...")
small_backup_files = [
    '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_044735',
    '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_140542',
    '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_143027',
    '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_143605'
]

for backup_file in small_backup_files:
    try:
        if os.path.exists(backup_file):
            size_mb = os.path.getsize(backup_file) / (1024 * 1024)
            if size_mb < 0.1:  # 100KB 미만 파일 삭제
                os.remove(backup_file)
                print(f"🗑️ 삭제됨: {os.path.basename(backup_file)} ({size_mb:.2f} MB)")
    except Exception as e:
        print(f"❌ 삭제 실패 {backup_file}: {e}")

print("\n✅ 데이터베이스 복구 작업 완료!")

🔧 데이터베이스 복구 작업 시작...
📦 복구 소스: stock_data.db.backup_20250727_044639 (3.76 MB)
✅ 로컬 DB 복구 완료: /home/grey1/stock-kafka3/data/duckdb/stock_data.db
❌ 로컬 DB 복구 실패: Catalog Error: Failure while replaying WAL file "/home/grey1/stock-kafka3/data/duckdb/stock_data.db.wal": Table with name "nasdaq_symbols" already exists!
✅ Airflow DB 복구 완료: /data/duckdb/stock_data.db
✅ 파일 권한 설정 완료

🧹 오래된 백업 파일 정리...
🗑️ 삭제됨: stock_data.db.backup_20250727_044735 (0.01 MB)
🗑️ 삭제됨: stock_data.db.backup_20250727_140542 (0.01 MB)
🗑️ 삭제됨: stock_data.db.backup_20250727_143027 (0.01 MB)
🗑️ 삭제됨: stock_data.db.backup_20250727_143605 (0.01 MB)

✅ 데이터베이스 복구 작업 완료!

In [ ]:
# WAL 파일 문제 해결 및 깨끗한 DB 재생성
import os
import duckdb

print("🔧 WAL 파일 문제 해결...")

# 1. WAL 파일 삭제
wal_file = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.wal'
if os.path.exists(wal_file):
    os.remove(wal_file)
    print("🗑️ WAL 파일 삭제 완료")

# 2. 기존 메인 DB 파일 삭제
main_db_path = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db'
if os.path.exists(main_db_path):
    os.remove(main_db_path)
    print("🗑️ 기존 메인 DB 파일 삭제")

# 3. 백업에서 새로운 DB 생성 (WAL 없이)
source_file = '/home/grey1/stock-kafka3/data/duckdb/stock_data.db.backup_20250727_044639'

try:
    # 소스 파일 연결 및 모든 데이터 추출
    source_con = duckdb.connect(database=source_file, read_only=True)
    
    # 새 DB 파일 생성
    new_con = duckdb.connect(database=main_db_path)
    
    # 테이블 목록 가져오기
    tables = source_con.execute("SHOW TABLES").fetchall()
    print(f"📊 복사할 테이블 수: {len(tables)}")
    
    for table in tables:
        table_name = table[0]
        print(f"  📋 복사 중: {table_name}")
        
        # 테이블 스키마 가져오기
        schema_info = source_con.execute(f"PRAGMA table_info('{table_name}')").fetchall()
        
        # CREATE TABLE 문 생성
        columns = []
        for col in schema_info:
            col_name, col_type, not_null, default_value, pk = col[1], col[2], col[3], col[4], col[5]
            col_def = f"{col_name} {col_type}"
            if not_null:
                col_def += " NOT NULL"
            if pk:
                col_def += " PRIMARY KEY"
            columns.append(col_def)
        
        create_sql = f"CREATE TABLE {table_name} ({', '.join(columns)})"
        new_con.execute(create_sql)
        
        # 데이터 복사
        data = source_con.execute(f"SELECT * FROM {table_name}").fetchall()
        if data:
            placeholders = ', '.join(['?' for _ in range(len(schema_info))])
            insert_sql = f"INSERT INTO {table_name} VALUES ({placeholders})"
            new_con.executemany(insert_sql, data)
        
        count = len(data)
        print(f"    ✅ {count:,}개 레코드 복사 완료")
    
    source_con.close()
    new_con.close()
    
    print("✅ 깨끗한 DB 파일 생성 완료")
    
    # 4. Airflow 경로로 복사
    airflow_db_path = '/data/duckdb/stock_data.db'
    if os.path.exists(airflow_db_path):
        os.remove(airflow_db_path)
    
    shutil.copy2(main_db_path, airflow_db_path)
    os.chmod(airflow_db_path, 0o666)
    print("✅ Airflow DB 복사 완료")
    
    # 5. 검증
    verify_con = duckdb.connect(database=main_db_path, read_only=True)
    tables = verify_con.execute("SHOW TABLES").fetchall()
    print(f"\n🔍 검증 결과: {len(tables)}개 테이블")
    
    for table in tables:
        table_name = table[0]
        count = verify_con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
        print(f"  📊 {table_name}: {count:,}개 레코드")
    
    verify_con.close()
    
except Exception as e:
    print(f"❌ DB 재생성 실패: {e}")

print("\n✅ 모든 복구 작업 완료!")

🔧 WAL 파일 문제 해결...
🗑️ WAL 파일 삭제 완료
🗑️ 기존 메인 DB 파일 삭제
📊 복사할 테이블 수: 6
  📋 복사 중: daily_watchlist
    ✅ 1개 레코드 복사 완료
  📋 복사 중: nasdaq_symbols